user default off
user REDIS_SESSION_USER_USERNAME on >REDIS_SESSION_USER_PASSWORD ~session:* +GET +SETEX +DEL +SCAN
user REDIS_REFRESH_USER_USERNAME on >REDIS_REFRESH_USER_PASSWORD ~refresh:* +GET +SETEX +DEL +SCAN

maxmemory 128MB
maxmemory-policy allkeys-lfu
save ""
